require 'spec_helper'

# The normal parser can't handle whitepace or newlines but we strip them out so that you can
# add newlines if preferred
FOO_ENC = "ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQE
BBQAEggEAkHeLWY+nDYcVJcK4e0ASbCO/DgBFXoU4G02J+QqOJpkAQg3CX6KhxzuQyNwLwvqElFdICfxHIXSgO6Pw76taDW8P
rTBR5Lmv38Z5mC0aIL9hwOTRlvyyx4fkLM4CFBGVbpVSzFmJ6PEgvaosG2hYjKiColIgcLG4JISRHnPOsveDHaDs3AqpRr4TRJIV2v4skYieJM6cWJ93s+maO
UCNDunWXrcQQpIYahj8WrYmqmf4sE1bpqtNqTMicCtGV32IccIieB1Sqzlw6YOtu6/e6NDmUzxNqXRcbIGIXNfrLM/nOpmXepRJ9MhlnGwYQ6C+0CPbNKrfwymSVirgUMpGKDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA9Wfkfu+oGYAx2XZGmRdQqgBBcolP8SXZ0l+tPHKg6a3H7]"

describe 'eyaml_tools::decrypt' do
 it { is_expected.to run.with_params(FOO_ENC).and_return('foo') }
end