---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.0
  - 2.2.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.5.0"
